
services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-symfony}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      
  php:
        build: .
        container_name: symfony_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - database
        environment:
          DATABASE_URL: postgres://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-symfony}@database:5432/${POSTGRES_DB:-app}
          MESSENGER_TRANSPORT_DSN: doctrine://default
          MAILER_DSN: smtp://mailer:1025
    
  messenger_worker:
        build: .
        restart: always
        depends_on:
            - php
            - database
        command: php bin/console messenger:consume async -vv
        volumes:
            - .:/var/www
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
