--
-- PostgreSQL database dump
--

-- Dumped from database version 14.17 (Homebrew)
-- Dumped by pg_dump version 14.17 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: notify_messenger_messages(); Type: FUNCTION; Schema: public; Owner: app
--

CREATE FUNCTION public.notify_messenger_messages() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
        PERFORM pg_notify('messenger_messages', NEW.queue_name::text);
        RETURN NEW;
    END;
$$;


ALTER FUNCTION public.notify_messenger_messages() OWNER TO app;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: carts; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.carts (
    uuid uuid NOT NULL,
    user_uuid uuid
);


ALTER TABLE public.carts OWNER TO app;

--
-- Name: categories; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.categories (
    uuid uuid NOT NULL,
    parent_uuid uuid,
    category_name character varying(64),
    prod_characteristics json
);


ALTER TABLE public.categories OWNER TO app;

--
-- Name: email_messages; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.email_messages (
    id integer NOT NULL,
    recipient character varying(255) NOT NULL,
    subject character varying(255) NOT NULL,
    body text NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    sent_at timestamp without time zone
);


ALTER TABLE public.email_messages OWNER TO app;

--
-- Name: email_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

CREATE SEQUENCE public.email_messages_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.email_messages_id_seq OWNER TO app;

--
-- Name: email_messages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: app
--

ALTER SEQUENCE public.email_messages_id_seq OWNED BY public.email_messages.id;


--
-- Name: in_delivery; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.in_delivery (
    uuid uuid NOT NULL,
    user_uuid uuid,
    item_uuid uuid
);


ALTER TABLE public.in_delivery OWNER TO app;

--
-- Name: item_statuses; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.item_statuses (
    id integer NOT NULL,
    name character varying(128)
);


ALTER TABLE public.item_statuses OWNER TO app;

--
-- Name: item_statuses_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

CREATE SEQUENCE public.item_statuses_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.item_statuses_id_seq OWNER TO app;

--
-- Name: item_statuses_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: app
--

ALTER SEQUENCE public.item_statuses_id_seq OWNED BY public.item_statuses.id;


--
-- Name: items; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.items (
    uuid uuid NOT NULL,
    product_uuid uuid,
    info json,
    status integer,
    location_uuid uuid,
    accessible boolean
);


ALTER TABLE public.items OWNER TO app;

--
-- Name: messenger_messages; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.messenger_messages (
    id bigint NOT NULL,
    body text NOT NULL,
    headers text NOT NULL,
    queue_name character varying(190) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    available_at timestamp(0) without time zone NOT NULL,
    delivered_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


ALTER TABLE public.messenger_messages OWNER TO app;

--
-- Name: messenger_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messenger_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_statuses; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.order_statuses (
    id integer NOT NULL,
    name character varying(255)
);


ALTER TABLE public.order_statuses OWNER TO app;

--
-- Name: order_statuses_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

CREATE SEQUENCE public.order_statuses_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.order_statuses_id_seq OWNER TO app;

--
-- Name: order_statuses_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: app
--

ALTER SEQUENCE public.order_statuses_id_seq OWNED BY public.order_statuses.id;


--
-- Name: orders; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.orders (
    uuid uuid NOT NULL,
    cart_uuid uuid,
    status integer
);


ALTER TABLE public.orders OWNER TO app;

--
-- Name: prices; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.prices (
    uuid uuid NOT NULL,
    price integer,
    product_uuid uuid,
    sale_uuid uuid
);


ALTER TABLE public.prices OWNER TO app;

--
-- Name: products; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.products (
    uuid uuid NOT NULL,
    info json,
    category_uuid uuid NOT NULL,
    price_uuid uuid
);


ALTER TABLE public.products OWNER TO app;

--
-- Name: products_in_carts; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.products_in_carts (
    product_uuid uuid NOT NULL,
    cart_uuid uuid NOT NULL,
    amount integer
);


ALTER TABLE public.products_in_carts OWNER TO app;

--
-- Name: roles; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.roles (
    uuid uuid NOT NULL,
    info json
);


ALTER TABLE public.roles OWNER TO app;

--
-- Name: sales; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.sales (
    uuid uuid NOT NULL
);


ALTER TABLE public.sales OWNER TO app;

--
-- Name: shops; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.shops (
    uuid uuid NOT NULL,
    address text
);


ALTER TABLE public.shops OWNER TO app;

--
-- Name: users; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.users (
    uuid uuid NOT NULL,
    info jsonb,
    role_uuid uuid,
    balance integer
);


ALTER TABLE public.users OWNER TO app;

--
-- Name: warehouses; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.warehouses (
    uuid uuid NOT NULL,
    address text
);


ALTER TABLE public.warehouses OWNER TO app;

--
-- Name: email_messages id; Type: DEFAULT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.email_messages ALTER COLUMN id SET DEFAULT nextval('public.email_messages_id_seq'::regclass);


--
-- Name: item_statuses id; Type: DEFAULT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.item_statuses ALTER COLUMN id SET DEFAULT nextval('public.item_statuses_id_seq'::regclass);


--
-- Name: order_statuses id; Type: DEFAULT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.order_statuses ALTER COLUMN id SET DEFAULT nextval('public.order_statuses_id_seq'::regclass);


--
-- Data for Name: carts; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.carts (uuid, user_uuid) FROM stdin;
d6e87223-e53b-4745-991e-342ee944bc3b	067607d9-f647-4b0f-b1b8-7556f137b00b
32909912-4cc7-4e28-81f4-82e3ac96e955	067607d9-f647-4b0f-b1b8-7556f137b00b
\.


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.categories (uuid, parent_uuid, category_name, prod_characteristics) FROM stdin;
98926c07-98a4-4bcf-ba69-265ce87a2970	\N	consumables	\N
6ac54748-a6b2-48aa-91fc-49832709e1fd	98926c07-98a4-4bcf-ba69-265ce87a2970	potions	\N
280ad4de-a054-4065-b5a7-6d2a8ce48a4a	6ac54748-a6b2-48aa-91fc-49832709e1fd	health_potions	\N
b2b6d163-9957-4ef7-9499-5a27860fb9ae	6ac54748-a6b2-48aa-91fc-49832709e1fd	mana_potions	\N
b156eade-1e14-4223-9f0b-e6cb4d797ec9	98926c07-98a4-4bcf-ba69-265ce87a2970	food	\N
\.


--
-- Data for Name: email_messages; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.email_messages (id, recipient, subject, body, status, created_at, sent_at) FROM stdin;
12	eeoneraiv.ty12@gmail.com	your purchase	you made an order	sent	2025-05-05 17:47:06	2025-05-05 17:47:08
\.


--
-- Data for Name: in_delivery; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.in_delivery (uuid, user_uuid, item_uuid) FROM stdin;
\.


--
-- Data for Name: item_statuses; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.item_statuses (id, name) FROM stdin;
1	in_warehouse
2	packing
\.


--
-- Data for Name: items; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.items (uuid, product_uuid, info, status, location_uuid, accessible) FROM stdin;
28ed891b-37f3-4013-ad4f-90cc56e073da	f3810995-6503-46d4-b766-57ea082bd6b6	{}	2	98e08727-f1bb-4d11-9c27-44b0d5fa9f8e	f
c52b0dbb-d9e5-4614-9d3f-951a63ac8ee1	f3810995-6503-46d4-b766-57ea082bd6b6	{}	2	98e08727-f1bb-4d11-9c27-44b0d5fa9f8e	f
084560a1-1e28-483b-8672-9f2c63d230f8	f3810995-6503-46d4-b766-57ea082bd6b6	{}	2	98e08727-f1bb-4d11-9c27-44b0d5fa9f8e	f
8d634986-b889-4f46-8232-3478a55d1b25	5fa266fa-2645-4612-82a8-5f0bd0212fca	{}	2	98e08727-f1bb-4d11-9c27-44b0d5fa9f8e	f
bc1f4ae8-7049-4d0a-81a1-34a1aa522f76	bc568f7c-1f60-472d-ace1-27cfc7bc83d3	{}	2	98e08727-f1bb-4d11-9c27-44b0d5fa9f8e	f
4f6524ee-1d18-4f23-8eca-57c4a3e9e912	bc568f7c-1f60-472d-ace1-27cfc7bc83d3	{}	2	98e08727-f1bb-4d11-9c27-44b0d5fa9f8e	f
\.


--
-- Data for Name: messenger_messages; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.messenger_messages (id, body, headers, queue_name, created_at, available_at, delivered_at) FROM stdin;
\.


--
-- Data for Name: order_statuses; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.order_statuses (id, name) FROM stdin;
1	created
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.orders (uuid, cart_uuid, status) FROM stdin;
5ee7a1de-1734-476d-a4bb-a27f3e2e6808	d6e87223-e53b-4745-991e-342ee944bc3b	1
\.


--
-- Data for Name: prices; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.prices (uuid, price, product_uuid, sale_uuid) FROM stdin;
763623a6-d629-4bb3-8053-5e250f53f3fc	100	bc568f7c-1f60-472d-ace1-27cfc7bc83d3	\N
711e1a5e-7b1a-44f7-b59a-c93aa0973d03	1500	5fa266fa-2645-4612-82a8-5f0bd0212fca	\N
31ebf4cf-e7a5-4eaf-b710-e1f9c0c4ee84	1000	f3810995-6503-46d4-b766-57ea082bd6b6	\N
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.products (uuid, info, category_uuid, price_uuid) FROM stdin;
f3810995-6503-46d4-b766-57ea082bd6b6	{"name":"omega_health_potion","characteristics":{"factory":"omega"}}	280ad4de-a054-4065-b5a7-6d2a8ce48a4a	31ebf4cf-e7a5-4eaf-b710-e1f9c0c4ee84
5fa266fa-2645-4612-82a8-5f0bd0212fca	{"name":"amazing_things_mana_potion","characteristics":{"factory":"amazing_things"}}	b2b6d163-9957-4ef7-9499-5a27860fb9ae	711e1a5e-7b1a-44f7-b59a-c93aa0973d03
bc568f7c-1f60-472d-ace1-27cfc7bc83d3	{"name":"super_dust","characteristics":{"factory":"Entropical_community"}}	98926c07-98a4-4bcf-ba69-265ce87a2970	763623a6-d629-4bb3-8053-5e250f53f3fc
120da175-0b82-4aaf-b440-ba4ccf1078c6	{"name":"Chaos_sphere","characteristics":{"factory":"Entropical_community"}}	98926c07-98a4-4bcf-ba69-265ce87a2970	\N
\.


--
-- Data for Name: products_in_carts; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.products_in_carts (product_uuid, cart_uuid, amount) FROM stdin;
f3810995-6503-46d4-b766-57ea082bd6b6	d6e87223-e53b-4745-991e-342ee944bc3b	3
5fa266fa-2645-4612-82a8-5f0bd0212fca	d6e87223-e53b-4745-991e-342ee944bc3b	1
bc568f7c-1f60-472d-ace1-27cfc7bc83d3	d6e87223-e53b-4745-991e-342ee944bc3b	2
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.roles (uuid, info) FROM stdin;
7d0d590f-4596-4e4f-8a94-939f5c15b46b	{"name":"guest"}
\.


--
-- Data for Name: sales; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.sales (uuid) FROM stdin;
\.


--
-- Data for Name: shops; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.shops (uuid, address) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.users (uuid, info, role_uuid, balance) FROM stdin;
24953abf-cfa2-429b-b6e3-861200b32a3e	{"name": "RANDOM", "password": "RANDOM"}	7d0d590f-4596-4e4f-8a94-939f5c15b46b	\N
067607d9-f647-4b0f-b1b8-7556f137b00b	{"name": "QWERTY", "password": "87654321"}	7d0d590f-4596-4e4f-8a94-939f5c15b46b	100
\.


--
-- Data for Name: warehouses; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.warehouses (uuid, address) FROM stdin;
98e08727-f1bb-4d11-9c27-44b0d5fa9f8e	Stormwind, mage district
\.


--
-- Name: email_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app
--

SELECT pg_catalog.setval('public.email_messages_id_seq', 12, true);


--
-- Name: item_statuses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app
--

SELECT pg_catalog.setval('public.item_statuses_id_seq', 2, true);


--
-- Name: messenger_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app
--

SELECT pg_catalog.setval('public.messenger_messages_id_seq', 27, true);


--
-- Name: order_statuses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app
--

SELECT pg_catalog.setval('public.order_statuses_id_seq', 1, true);


--
-- Name: carts carts_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (uuid);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (uuid);


--
-- Name: email_messages email_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.email_messages
    ADD CONSTRAINT email_messages_pkey PRIMARY KEY (id);


--
-- Name: in_delivery in_delivery_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.in_delivery
    ADD CONSTRAINT in_delivery_pkey PRIMARY KEY (uuid);


--
-- Name: in_delivery in_delivery_user_uuid_item_uuid_key; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.in_delivery
    ADD CONSTRAINT in_delivery_user_uuid_item_uuid_key UNIQUE (user_uuid, item_uuid);


--
-- Name: item_statuses item_statuses_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.item_statuses
    ADD CONSTRAINT item_statuses_pkey PRIMARY KEY (id);


--
-- Name: items items_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_pkey PRIMARY KEY (uuid);


--
-- Name: messenger_messages messenger_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.messenger_messages
    ADD CONSTRAINT messenger_messages_pkey PRIMARY KEY (id);


--
-- Name: order_statuses order_statuses_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.order_statuses
    ADD CONSTRAINT order_statuses_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (uuid);


--
-- Name: prices prices_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.prices
    ADD CONSTRAINT prices_pkey PRIMARY KEY (uuid);


--
-- Name: products_in_carts products_in_carts_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.products_in_carts
    ADD CONSTRAINT products_in_carts_pkey PRIMARY KEY (product_uuid, cart_uuid);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (uuid);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (uuid);


--
-- Name: sales sales_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT sales_pkey PRIMARY KEY (uuid);


--
-- Name: shops shops_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.shops
    ADD CONSTRAINT shops_pkey PRIMARY KEY (uuid);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (uuid);


--
-- Name: warehouses warehouses_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.warehouses
    ADD CONSTRAINT warehouses_pkey PRIMARY KEY (uuid);


--
-- Name: idx_75ea56e016ba31db; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX idx_75ea56e016ba31db ON public.messenger_messages USING btree (delivered_at);


--
-- Name: idx_75ea56e0e3bd61ce; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX idx_75ea56e0e3bd61ce ON public.messenger_messages USING btree (available_at);


--
-- Name: idx_75ea56e0fb7336f0; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX idx_75ea56e0fb7336f0 ON public.messenger_messages USING btree (queue_name);


--
-- Name: messenger_messages notify_trigger; Type: TRIGGER; Schema: public; Owner: app
--

CREATE TRIGGER notify_trigger AFTER INSERT OR UPDATE ON public.messenger_messages FOR EACH ROW EXECUTE FUNCTION public.notify_messenger_messages();


--
-- Name: carts carts_user_uuid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_user_uuid_fkey FOREIGN KEY (user_uuid) REFERENCES public.users(uuid);


--
-- Name: products fk_price; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fk_price FOREIGN KEY (price_uuid) REFERENCES public.prices(uuid);


--
-- Name: items items_product_uuid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_product_uuid_fkey FOREIGN KEY (product_uuid) REFERENCES public.products(uuid);


--
-- Name: items items_status_fkey; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_status_fkey FOREIGN KEY (status) REFERENCES public.item_statuses(id);


--
-- Name: orders orders_cart_uuid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_cart_uuid_fkey FOREIGN KEY (cart_uuid) REFERENCES public.carts(uuid);


--
-- Name: orders orders_status_fkey; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_status_fkey FOREIGN KEY (status) REFERENCES public.order_statuses(id);


--
-- Name: prices prices_product_uuid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.prices
    ADD CONSTRAINT prices_product_uuid_fkey FOREIGN KEY (product_uuid) REFERENCES public.products(uuid);


--
-- Name: prices prices_sale_uuid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.prices
    ADD CONSTRAINT prices_sale_uuid_fkey FOREIGN KEY (sale_uuid) REFERENCES public.sales(uuid);


--
-- Name: products products_category_uuid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_category_uuid_fkey FOREIGN KEY (category_uuid) REFERENCES public.categories(uuid) ON DELETE CASCADE;


--
-- Name: products_in_carts products_in_carts_cart_uuid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.products_in_carts
    ADD CONSTRAINT products_in_carts_cart_uuid_fkey FOREIGN KEY (cart_uuid) REFERENCES public.carts(uuid);


--
-- Name: products_in_carts products_in_carts_product_uuid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.products_in_carts
    ADD CONSTRAINT products_in_carts_product_uuid_fkey FOREIGN KEY (product_uuid) REFERENCES public.products(uuid);


--
-- Name: users users_role_uuid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_role_uuid_fkey FOREIGN KEY (role_uuid) REFERENCES public.roles(uuid);


--
-- PostgreSQL database dump complete
--

